### ISSUE TITLE
Postee sending empty email for scanned image

### ISSUE THREAD

**Issue by indrajithgihan** [aquasecurity/trivy-plugin-webhook#20]
Getting empty report via email for image scan.

### Received Email results:

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/d7708d6e-645e-4af2-b62d-e77b32b4a2a6">

### cfg.yaml
 ```
   actions:
      - type: email
        name: my-email
        user:
        host: x.x.x.x
        port: 25
        sender: xxxx@xxx.com
        recipients:
          - xxxx
        password:
        enable: true
    routes:
      - name: email-route
        input: contains(input.Metadata.OS.Family, "alpine")
        #input: |
          #contains(input.image,"alpine")
        #input: input
        actions:
          - my-email
        template: legacy       
    templates:
      - name: slack-template
        rego-package: postee.vuls.slack
      - name: rego-html
        rego-package: postee.vuls.html
      - name: legacy
        legacy-scan-renderer: html
      - name: legacy-slack
        legacy-scan-renderer: slack
      - name: custom-email
        url: null
      - name: trivy-operator-jira
        rego-package: postee.trivyoperator.jira
      - name: trivy-operator-slack
        rego-package: postee.trivyoperator.slack
        templates:
      - name: trivy-raw-json
        rego-package: postee.rawmessage.json
    name: tenant
    AquaServer: https://xxxxxxxxxxx.com
```

### Trivy webhook run command:

`trivy webhook --url=http://postee-service.trivy-tools.svc.cluster.local:8084 -- image <image name>  --format=json --ignore-unfixed --severity HIGH,CRITICAL,MEDIUM`

### Postee log:

<img width="668" alt="image" src="https://github.com/user-attachments/assets/54626417-a475-414b-ac2d-b2bb66bc2637">

### Trivy webhook run command result:

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/9b08f26b-55b1-49cd-a8a1-896640fa871c">
